// src/lib/mock.js
export const productos = [
  {
    id: "p1",
    titulo: "Colores 24 pzs",
    precio: 169,
    badge: "Nuevo",
    image: "/products/colores.webp", // <— ruta relativa a /public
  },
  {
    id: "p2",
    titulo: "Cuaderno Pro A5",
    precio: 89,
    badge: "Top",
    image: "/products/cuaderno.jpg",
  },
  {
    id: "p3",
    titulo: "Marcadores 5p",
    precio: 75,
    badge: "Oferta",
    image: "/products/marcadores.webp",
  },
  {
    id: "p4",
    titulo: "Tijeras Junior",
    precio: 55,
    badge: "Nuevo",
    image: "/products/tijeras.png",
  },
  {
    id: "p5",
    titulo: "Borrador FACTIS (20 pzs)",
    precio: 120,
    badge: "Básico",
    categoria: "Papelería",
    image: "/products/borrador.webp",
  },
  {
    id: "p6",
    titulo: "Lápices HB (12 pzs)",
    precio: 79,
    badge: "Pack",
    categoria: "Escolares",
    image: "/products/lapices.jpg",
  },
  {
    id: "p7",
    titulo: "Lapiceros gel (6 pzs)",
    precio: 95,
    badge: "Recomendado",
    categoria: "Oficina",
    image: "/products/lapiceros.jpg",
  },
  {
    id: "p8",
    titulo: "Resistol DIXON (30 pzs)",
    precio: 115,
    badge: "Top",
    categoria: "Escolares",
    image: "/products/resistol.webp",
  },
  {
    id: "p9",
    titulo: "Lapiceros tinta negra (12 pzs)",
    precio: 110,
    badge: "Pack",
    categoria: "Oficina",
    image: "/products/lapiceros_negros.jpeg",
  },
  {
    id: "p10",
    titulo: "Corrector líquido 20 ml",
    precio: 32,
    badge: "Básico",
    categoria: "Oficina",
    image: "/products/corrector.jpeg",
  },
  {
    id: "p11",
    titulo: "Zacapuntas MAPED",
    precio: 25,
    badge: "Ahorro",
    categoria: "Escolares",
    image: "/products/zacapuntas.jpeg",
  },
  {
    id: "p12",
    titulo: "Juego Geometrico",
    precio: 18,
    badge: "Básico",
    categoria: "Papelería",
    image: "/products/juego_geometrico.jpg",
  },
];
